<script lang="ts">
  import AgentResponse from "$lib/components/agents-ui/agent-response.svelte";
  import AgentRevenueInsights from "$lib/components/agents-ui/agent-revenue-insights.svelte";
  import AgentTaskQueue, {
    type AgentTask,
  } from "$lib/components/agents-ui/agent-task-queue.svelte";
  import AgentWorkflowPlanner, {
    type ActionItem,
    type WorkflowCheckpoint,
    type WorkflowPlaybook,
  } from "$lib/components/agents-ui/agent-workflow-planner.svelte";

  const tasks: AgentTask[] = [
    {
      id: "launch-email-1",
      title: "QA production checklist",
      description: "Verify pricing toggle + onboarding tour",
      status: "running",
      progress: 58,
      priority: "high",
      estimatedDuration: "~2 min remaining",
      tool: "Launch auditor",
      updatedLabel: "Running • 4 min ago",
      checkpoints: [
        { id: "l-e1", title: "Smoke test", status: "completed", timestamp: "08:05" },
        { id: "l-e2", title: "Toggle validation", status: "active", timestamp: "08:09" },
        { id: "l-e3", title: "Final approval", status: "pending" },
      ],
      metrics: { tokens: 780, confidence: 0.84 },
    },
    {
      id: "launch-email-2",
      title: "Prep announcement email",
      description: "Translate AI summary to human voice",
      status: "queued",
      priority: "medium",
      tool: "Copy agent",
      updatedLabel: "Queued behind 1 task",
    },
    {
      id: "launch-email-3",
      title: "Update help center",
      description: "Publish release notes + FAQ",
      status: "completed",
      progress: 100,
      priority: "medium",
      tool: "Docs agent",
      updatedLabel: "Completed 07:42",
    },
  ];

  const checkpoints: WorkflowCheckpoint[] = [
    {
      id: "workflow-1",
      title: "Finalize pricing page",
      owner: "Agent Atlas",
      eta: "Today 12:00",
      status: "done",
      notes: "Localized strings locked in",
    },
    {
      id: "workflow-2",
      title: "Enable lifecycle automations",
      owner: "Agent Relay",
      eta: "Today 16:00",
      status: "active",
      notes: "Syncing segments from HubSpot",
    },
    {
      id: "workflow-3",
      title: "Sales enablement pack",
      owner: "Agent Story",
      eta: "Tomorrow 09:00",
      status: "upcoming",
      notes: "Needs final approval from revenue ops",
    },
  ];

  const playbooks: WorkflowPlaybook[] = [
    {
      label: "Announcement choreography",
      description: "Email + in-app + social go-live in under 30 min",
      tasks: ["Draft launch email", "Schedule in-app banner", "Queue social threads"],
      handoff: "Marketing manager sign-off",
    },
  ];

  const actions: ActionItem[] = [
    {
      id: "action-1",
      label: "Review translation",
      detail: "Agent Relay awaiting approval on ES/DE localized email",
      type: "human",
    },
    {
      id: "action-2",
      label: "Generate hero assets",
      detail: "Agent Canvas producing 3 hero variations",
      type: "agent",
    },
  ];
</script>

<div
  class="mx-auto flex max-w-5xl flex-col gap-6 rounded-2xl border bg-background p-6 shadow-sm"
>
  <div class="flex flex-col gap-1">
    <span class="text-xs font-medium uppercase tracking-wide text-blue-600"
      >Launch Digest</span
    >
    <h2 class="text-2xl font-semibold tracking-tight">
      Week 14 · Ship the Onboarding Bundle
    </h2>
    <p class="text-sm text-muted-foreground">
      Sent via product@acmeco.com · Generated by Launch Agent • March 21, 2025
    </p>
  </div>

  <AgentResponse
    class="border border-dashed"
    message={`## Summary
- ✅ Pricing page updates deployed this morning.
- 🚀 Lifecycle automations queued for 4pm global rollout.
- 🤝 Sales enablement pack due tomorrow for revenue alignment.

### Key Risks
1. Localized email copy awaiting final approval.
2. Need final confirmation on hub sync post-rollout.
3. Social threads require hero asset selection.
        `}
    thinking="Assemble highlights from revenue, ops, and marketing agents before emailing leadership."
  />

  <div class="grid gap-6 lg:grid-cols-[1.1fr,0.9fr]">
    <AgentRevenueInsights
      class="w-full"
      currentArr="$480k"
      arrChange="+11.8%"
      periodLabel="Projected ARR impact · Next 60 days"
      scenario="stretch"
      forecastPoints={[
        { label: "Apr", value: 7.4 },
        { label: "May", value: 8.1 },
        { label: "Jun", value: 9.2 },
        { label: "Jul", value: 9.8 },
        { label: "Aug", value: 10.6 },
        { label: "Sep", value: 11.4 },
      ]}
      segmentInsights={[
        {
          id: "growth",
          segment: "Growth · Self-serve",
          arr: "$240k",
          trend: "up",
          change: "+18%",
          confidence: 0.82,
          owner: "Agent Ledger",
        },
        {
          id: "enterprise",
          segment: "Enterprise · Expansion",
          arr: "$160k",
          trend: "up",
          change: "+9%",
          confidence: 0.78,
          owner: "Agent Relay",
        },
      ]}
    />

    <AgentTaskQueue
      class="w-full"
      {tasks}
      autoStart
      concurrencyLimit={2}
      timestamp="Digest generated 08:20"
    />
  </div>

  <AgentWorkflowPlanner
    class="mx-auto w-full max-w-5xl"
    programName="Launch choreography"
    timeframe="March 18 - 22"
    {checkpoints}
    {playbooks}
    nextActions={actions}
  />
</div>
