/**
 * agentic-ui-kit — Svelte 5 port of agents-ui-kit + prompt-kit.
 * Import components from package subpaths or this barrel as exports land.
 */
export { cn } from "./utils.js";
export {
  theme,
  initTheme,
  setTheme,
  toggleTheme,
  cycleTheme,
  resolvedTheme,
  type Theme,
} from "./theme.svelte.js";

export * from "./components/ui/index.js";

export {
  AgentImageEditor,
  AgentVideoEditor,
  AgentAudioGenerator,
  AgentGrammarChecker,
  AgentArtifact,
  AgentFormGenerator,
  AgentCodeExecutor,
  AgentDocScanner,
  AgentWebSearch,
} from "./components/agents-ui/index.js";

export type {
  ImageVariation,
  AgentImageEditorProps,
  VideoClip,
  AgentVideoEditorProps,
  VoiceOption,
  AgentAudioGeneratorProps,
  GrammarIssueType,
  GrammarIssue,
  GrammarStats,
  AgentGrammarCheckerProps,
  ArtifactType,
  ArtifactVersion,
  ArtifactMetadata,
  AgentArtifactProps,
  FormFieldType,
  FormFieldValidation,
  FormField,
  AgentFormGeneratorProps,
  CodeExecutionOutput,
  CodeExecutionHistoryItem,
  AgentCodeExecutorProps,
  ExtractedSection,
  DocumentInfo,
  AgentDocScannerProps,
  SearchResult,
  AgentWebSearchProps,
} from "./components/agents-ui/index.js";

// blocks (kit-blocks) — composition demos
export {
  ConversationWithActions,
  ConversationActions,
  ConversationWithAvatars,
  ConversationAvatars,
  ConversationPromptInput,
  ConversationWithScrollBottom,
  ConversationScrollBottom,
  EmailLaunchDigest,
  FullChatApp,
  FullConversation,
  MarketingFunnelCommandCenter,
  PromptAutocompleteHighlight,
  PromptInputWithActions,
  PromptInputWithSuggestions,
  SidebarChatHistory,
  SocialTrendAgent,
} from "./components/blocks/index.js";

// prompt-kit (kit-prompt)
export {
	ChatContainerRoot,
	ChatContainerContent,
	ChatContainerScrollAnchor,
	CodeBlock,
	CodeBlockCode,
	CodeBlockGroup,
	FileUpload,
	FileUploadTrigger,
	FileUploadContent,
	JSXPreview,
	Loader,
	Markdown,
	Message,
	MessageAvatar,
	MessageContent,
	MessageActions,
	MessageAction,
	PromptInput,
	PromptInputTextarea,
	PromptInputActions,
	PromptInputAction,
	PromptSuggestion,
	Reasoning,
	ReasoningTrigger,
	ReasoningContent,
	ResponseStream,
	useTextStream,
	ScrollButton,
} from "./components/prompt-kit/index.js";
export type {
	Mode,
	UseTextStreamOptions,
	UseTextStreamResult,
} from "./components/prompt-kit/index.js";

// agents-ui hitl (kit-agents-hitl)
export {
	AgentToolApproval,
	AgentPlanBuilder,
	AgentInquiry,
} from "./components/agents-ui/index.js";
export type {
	RiskLevel,
	ToolApprovalRequest,
	ToolApprovalHistoryItem,
	ToolExecutionResult,
	AgentToolApprovalProps,
	PlanStepStatus,
	PlanStep,
	AgentPlanBuilderProps,
	InquiryType,
	Inquiry,
	InquiryHistoryItem,
	AgentInquiryProps,
} from "./components/agents-ui/index.js";

// agents-ui analytics (kit-agents-analytics)
export {
	AgentAnalyticsPulse,
	AgentRevenueInsights,
	AgentDataAnalysis,
	AgentCompetitorResearch,
	AgentSourcesCitations,
} from "./components/agents-ui/index.js";
export type {
	PulseMetric,
	AttributionSlice,
	InsightHighlight,
	AgentAnalyticsPulseProps,
	RevenueForecastPoint,
	RevenueSegmentInsight,
	RevenueScenario,
	AgentRevenueInsightsProps,
	DataMetric,
	DataPreview,
	DataInsight,
	DistributionBar,
	AgentDataAnalysisProps,
	ResearchDepth,
	ThreatLevel,
	Competitor,
	ComparisonFeature,
	AgentCompetitorResearchProps,
	SourceType,
	CitationSource,
	AgentSourcesCitationsProps,
} from "./components/agents-ui/index.js";

// agents-ui core (kit-agents-core)
export {
	AgentCard,
	AgentResponse,
	AgentStatusPanel,
	AgentPromptComposer,
	AgentChatHistory,
	AgentToolPalette,
	AgentToolkit,
	AgentFeedback,
} from "./components/agents-ui/index.js";
export type {
	AgentStatus,
	AgentCapability,
	AgentCardProps,
	ToolCall,
	Artifact,
	AgentResponseProps,
	ConnectionStatus,
	ModelCapability,
	ModelInfo,
	SystemResources,
	AgentStatusPanelProps,
	PromptTemplate,
	Persona,
	AgentPromptComposerProps,
	ChatMessage,
	ChatSession,
	AgentChatHistoryProps,
	ToolCategory,
	AgentTool,
	AgentToolPaletteProps,
	FeedbackType,
	FeedbackCategory,
	FeedbackData,
	AgentFeedbackProps,
} from "./components/agents-ui/index.js";

// agents-ui ops (kit-agents-ops)
export {
	AgentOpsMonitor,
	AgentTaskQueue,
	AgentWorkflowPlanner,
	AgentOrchestrator,
	AgentParallelProcessor,
	AgentSequentialWorkflow,
	AgentRoutingHub,
	AgentEvaluator,
} from "./components/agents-ui/index.js";
export type {
	OpsSignal,
	OpsServiceMetric,
	IncidentEvent,
	AgentOpsMonitorProps,
	AgentTaskStatus,
	AgentTaskPriority,
	AgentTaskTimelineStatus,
	AgentTaskTimelineEvent,
	AgentTaskAssignee,
	AgentTask,
	AgentTaskQueueProps,
	WorkflowCheckpoint,
	WorkflowPlaybook,
	ActionItem,
	AgentWorkflowPlannerProps,
	SubAgentStatus,
	SubAgentMetrics,
	SubAgent,
	CommLogEntry,
	AgentOrchestratorProps,
	ParallelLaneStatus,
	ParallelLane,
	AgentParallelProcessorProps,
	WorkflowStepStatus,
	WorkflowStep,
	AgentSequentialWorkflowProps,
	RouteStatus,
	RouteClassification,
	AgentRoute,
	RoutingHistoryEntry,
	AgentRoutingHubProps,
	EvalCriterion,
	EvalIteration,
	AgentEvaluatorProps,
} from "./components/agents-ui/index.js";
